# services:
#   db:
#     image: mysql:8
#     container_name: my_sql
#     environment:
#       MYSQL_DATABASE: test
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_USER: user
#       MYSQL_PASSWORD: pass
#     ports:
#       - "6603:3306"
#     volumes:
#       - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
#     healthcheck:
#       test: ["CMD-SHELL", "mysql -u root -proot -e 'USE test;'"]
#       interval: 10s
#       timeout: 10s
#       retries: 5

#   backend:
#     build: 
#       context: ./backend
#       dockerfile: Dockerfile
#     depends_on:
#       db:
#         condition: service_healthy
#     container_name: my_backend
#     ports:
#       - "8800:8800"

#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     container_name: my_frontend
#     ports:
#       - "5173:5173"
#     depends_on:
#       - backend

version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my_backend
    ports:
      - "8800:8800"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
